name: Deploy Backend to EC2 - Production

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.PRODUCTION_SSH_KEY }}

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -v -o StrictHostKeyChecking=no ec2-user@3.148.249.47 "echo 'SSH connected'"

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.148.249.47 << 'EOF'
            cd /var/www/backend

            echo "Pulling latest code..."
            git pull origin prod

            echo "Installing dependencies..."
            npm install

            echo "Running Prisma deploy..."
            dotenv -e .env.production -- npx prisma migrate deploy

            echo "Restarting app with PM2..."
            pm2 restart backend || pm2 start npm --name "backend" -- run start

            echo "Deployment complete"
          EOF
